settings_version: 0.0.4
datasets_dir: /Users/henry/Localdev/emg-demo/datasets
weights_dir: /Users/henry/Localdev/emg-demo/weights
runs_dir: /Users/henry/Localdev/emg-demo/runs
uuid: fab08d79c217b2e6f9e6e72cf8816e9b7bbc4c074e952faa9732fc19150466e1
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
